### PR TITLE
F* changes in VC generation of conditionals

### PR DESCRIPTION
**Pull request by aseemr**
Aside from the flaky proofs, these two are the more interesting ones:

https://github.com/project-everest/hacl-star/commit/b6cac6031c39e7001da07437d07d4afd219d4f19

https://github.com/project-everest/hacl-star/commit/7c9bae41d2f00e88e5ef080208db090d00c277ab

I have added some comments for them in the files or the commit messages.

### CODE REVIEW

**Comment by msprotz** [comment]
you submitted all the hints with your pull request... is this intentional?

**Comment by msprotz** [comment]
thanks for fixing both of those!

**Comment by msprotz** [comment]
build failed:
```
[STDERR]Cloning into 'openssl'...
[STDOUT]echo "openssl folder is empty, running git submodule update... no recursion"
[STDOUT]openssl folder is empty, running git submodule update... no recursion
[STDERR]error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
[STDOUT]git submodule update --init
```

**Comment by msprotz** [comment]
Legitimate failure:
```
[STDERR]/home/everest/hacl-star/code/curve25519/Hacl.Spec.Curve25519.Field51.fst(90,2-92,16): (Error 16) Unknown assertion failed
[STDERR]	SMT solver says:
[STDERR]	unknown because canceled (fuel=0; ifuel=0);
[STDERR]	unknown because canceled (fuel=0; ifuel=0; with hint);
[STDERR]	Note: 'canceled' or 'resource limits reached' means the SMT query timed out, so you might want to increase the rlimit;
[STDERR]	'incomplete quantifiers' means a (partial) counterexample was found, so try to spell your proof out in greater detail, increase fuel or ifuel
[STDERR]	'unknown' means Z3 provided no further reason for the proof failing
[STDERR]Verified module: Hacl.Spec.Curve25519.Field51
```

**Comment by aseemr** [comment]
The proof is not even using a conditional, seems like a flaky non-linear arithmetic thing. Let me take a look.

Re. hints, I had these from a local successful run, so I submitted. I can remove them if that's an issue.

**Comment by msprotz** [comment]
Linux came back green, merging. Thanks Aseem.

**Pull request merged**
