### PR TITLE
Adding SHA-1

### PR DESCRIPTION
**Pull request by Frosne**
#### Summary

This PR adds support of SHA-1 for Mozilla.

### CODE REVIEW

**Comment by msprotz** [comment]
@Frosne any update on this? Thanks!

**Comment by Frosne** [comment]
Let me check and I will get back to it as soon as I can :)

**Comment by Frosne** [comment]
@msprotz, I think that enabling HMAC and HKDF is not so bad. I am pretty sure that our users could benefit from these functions as well, but it will be in (foreseeable, but still) future.

**Comment by msprotz** [comment]
Great, then I'll approve as soon as I see the list of new files in dist/mozilla -- we don't have nightly dist refresh anymore so it's important to know what this changes. Thanks!

**Comment by Frosne** [comment]
After the modification, a couple of new files were added: 

Hacl_HKDF.{c, h}, Hacl_HMAC*.{c, h},  Hacl_Hash_{MD5, SHA1, SHA2}.{c,h}, as well as the algorithms of Blake family

**Comment by Frosne** [comment]
It's very curious: I get an exception "dist/mozilla/Hacl_Impl_Blake2_Hacl_Blake2b_256_Hacl_Blake2s_128_Hacl_Blake2b_32_Hacl_Streaming_Blake2s_128_Hacl_Streaming_Blake2b_256_Hacl_Blake2s_32_Hacl_HMAC_Blake2b_256_Hacl_HMAC_Blake2s_128_Hacl_HKDF_Blake2b_256_Hacl_HKDF_Blake2s_128.c: Filename too long"

**Comment by msprotz** [comment]
> It's very curious: I get the exception "dist/mozilla/Hacl_Impl_Blake2_Hacl_Blake2b_256_Hacl_Blake2s_128_Hacl_Blake2b_32_Hacl_Streaming_Blake2s_128_Hacl_Streaming_Blake2b_256_Hacl_Blake2s_32_Hacl_HMAC_Blake2b_256_Hacl_HMAC_Blake2s_128_Hacl_HKDF_Blake2b_256_Hacl_HKDF_Blake2s_128.c: Filename too long"

Then I would append `[rename=Blake2_Should_Not_Be_Used]` to this line: https://github.com/project-everest/hacl-star/blob/master/Makefile#L964, run `make compile-mozilla` again, and see what this file contains to understand why krml can't get rid of it.

**Comment by Frosne** [comment]
Hello again,

[Blake*Should_Not_Be_Used] is added because of  the HMAC code it seems.

**Comment by msprotz** [comment]
This is normal: when you removed this line

```
HASH_BUNDLE = -bundle Hacl.Hash.*,Hacl.HKDF,Hacl.HMAC,Hacl.HMAC_DRBG
```

then you "enabled" HMAC&HKDF, which need Blake2, so Blake2 is now generated as well.

Is this intentional? Do you want to enable DRBG, HMAC and HKDF?

**Comment by Frosne** [comment]
Following the advice of @msprotz, we have updated dist/mozilla. Now the only files added are SHA1.{c,h}.

**Review by msprotz — APPROVED** [review]

**Review by beurdouche — APPROVED** [review]

**Pull request merged**
