### PR TITLE
Change Vale inclusion strategy

### PR DESCRIPTION
**Pull request by msprotz**
Thanks to https://github.com/FStarLang/kremlin/pull/230 we can now be more precise about how to include other headers. This includes the Vale primitives from the HACL C file only, which prevents scope pollution when clients of HACL include the HACL h file.

### CODE REVIEW

**Comment by franziskuskiefer** [comment]
> GitHub's runners seem to no longer have MSVC installed...?!

They do (see [Windows image](https://github.com/actions/virtual-environments/blob/win22/20220207.1/images/win/Windows2022-Readme.md)). But looks like the machines got updated and the VisualStudio version is hard coded to 2019. It's 2022 now.

https://github.com/project-everest/hacl-star/blob/d5ff35780aa10d383b44e6068d9ed20de78e09fa/.ci/script.bat#L1-L2

**Comment by msprotz** [comment]
Well that didn't work. You wouldn't happen to know the location of these files now, would you?

**Comment by msprotz** [comment]
Ok that worked. Thanks so much for the pointer!

**Review by Kachoc — APPROVED** [review]

**Comment by msprotz** [comment]
Temporary setback as I had to revert the kremlin side of changes... I'll try to fix it later today. Thanks.

**Comment by msprotz** [comment]
Aseem, any chance you can review this? (I'm trying to respect the convention that each PR has one MSR + one INRIA review.)

This contains a build fix that your PR needs in order to pass Windows CI on the updated GitHub actions containers. Thanks!

**Comment by msprotz** [comment]
```
503 Backend is unhealthy           Error 503
     | Backend is unhealthy     Backend is unhealthy     Guru
     | Mediation:     Details: cache-pdx12320-PDX 1645544331
     | 3972973316          Varnish cache server
``` 

This error seems unrelated to anything...?

**Review by aseemr — APPROVED** [review]

**Comment by msprotz** [comment]
Thanks Aseem!

**Pull request merged**
