### PR TITLE
Adapt uses of sigelt_view to changes in FStar#2291

### PR DESCRIPTION
**Pull request by antoniolocascio**
[FStarLang/FStar#2291](https://github.com/FStarLang/FStar/pull/2291) adds support for mutually recursive let-bindings in `sigelt_view`. To do so, the interface of the`Sg_Let` constructor changes, breaking some uses in HACL*. This PR fixes those uses.

### CODE REVIEW

**Review by msprotz — APPROVED** [review]
This is really great -- much appreciated! Did you get an Everest green with those changes?

**Comment by antoniolocascio** [comment]
I was able to build Everest, but I think my Everest setup is broken. Tests always fail, even without my changes.

**Comment by msprotz** [comment]
If it's just tests I'm not too worried. Some of them are notoriously broken (i.e. your CPU may not have the right instruction and the test targets don't really account for that.)

**Comment by msprotz** [comment]
As long as it verifies, this is good for me. You may want to ask @R1kM or @Kachoc for an extra review since they know this code

**Review by Kachoc — APPROVED** [review]
It looks good to me too. And I have the same position as @msprotz : as long as it verifies, it is good to me.

**Comment by msprotz** [comment]
Merging since CI won't run for external PRs in HACL (even after clicking the "approve" button), and @aseemr checked and got an Everest green.

Thanks again @antoniolocascio !!

**Pull request merged**
