### PR TITLE
make sure clang understands that r0-r3 are constants

### LINKED ISSUE #339: ARM builds with clang are broken
`clang` doesn't like the constants in `Hacl_Impl_Blake2_Constants_rTable_S` (`error: argument to '__builtin_neon_vsriq_n_v' must be a constant integer`). The integers here really are constants, but `clang` doesn't understand this. So instead of using `Hacl_Impl_Blake2_Constants_rTable_S` something like

```
#define Hacl_Impl_Blake2_Constants_rTable_S_0 16
#define Hacl_Impl_Blake2_Constants_rTable_S_1 12
#define Hacl_Impl_Blake2_Constants_rTable_S_2 8
#define Hacl_Impl_Blake2_Constants_rTable_S_3 7
```

could be used.

https://github.com/project-everest/hacl-star/blob/51054f0b49464d49654792dbdeb08460262bd4c5/dist/gcc-compatible/Hacl_Blake2s_128.c#L168

### PR DESCRIPTION
**Pull request by franziskuskiefer**
Fixes #339

### CODE REVIEW

**Comment by msprotz** [comment]
@franziskuskiefer owing to our CI system, there won't be a run unless you push to a branch of the main repository -- do you have the credentials to do that? other than that, looks good to me, thanks!!

**Comment by franziskuskiefer** [comment]
I only have access to the CI but not this repo 😬

**Comment by msprotz** [comment]
I've sent you an invitation. Do you mind pushing on a branch of project-everest/hacl-star to get a complete round of CI? It's required to be able to merge.

I would happily do it myself but then that would prevent me from approving your PR -- on GitHub, you can't approve a PR if you're the one who opened it.

Note that you may have to close this one in favor of a fresh PR with your new branch.

Thanks for your patience!

**Comment by franziskuskiefer** [comment]
Heh, no worries. I pushed to [franziskus/fix-neon-clang](https://github.com/project-everest/hacl-star/tree/franziskus/fix-neon-clang) and it looks like that's enough for the CI to start running. Not with a merged master though. I opened #341.

**Pull request closed without merging**
