### PR TITLE
Improvement to Chacha20Poly1305

### PR DESCRIPTION
**Pull request by beurdouche**

### CODE REVIEW

**Comment by beurdouche** [comment]
I've been able to test it locally and it passes the tests we have.

**Review by polubelova — APPROVED** [review]

**Comment by polubelova** [comment]
No surprise that it passes the tests. The fix is correct as `poly1305_update` returns the initial `acc` value if the input length is 0.
thanks @beurdouche!

**Comment by msprotz** [comment]
Can you add a C test that would make sure this case is caught? It's slightly worrying that this issue wasn't caught earlier -- it'd be good to catch this sort of bugs before they make it over to NSS.

**Comment by polubelova** [comment]
It's related to this one: https://github.com/project-everest/hacl-star/issues/327

**Comment by msprotz** [comment]
the UB is only in low-level C code, but here the spec too is changed, so it seems like there was a spec bug to begin with?

**Comment by polubelova** [comment]
One could just prove the following lemma:
```
val poly1305_padded_lemma:
    r_elem:Poly.felem
  -> text:bytes
  -> acc:Poly.felem -> Lemma
  (requires length text = 0)
  (ensures poly1305_padded r_elem text acc == acc)
```
With that, we won't need to change the spec.

**Comment by msprotz** [comment]
Two questions then.
- Why make the spec more complicated if this is just an implementation matter? The spec should remain as small as possible so that it can be audited.
- Does this mean that the issue from #327 resulted in a mis-compilation that was observed with NSS?

**Comment by beurdouche** [comment]
The spec should have been written this way from the beginning, it is an artifact of someone wanting to reuse the same code too aggressively without branching on `aadlen`. The semantics is if the length of AAD is zero, this function should not have been called at all.

**Comment by prosecco** [comment]
I don’t see a need to change the high-level spec, but this change is innoccuous.
Our specs follow the pseudocode in the RFC, e.g. https://tools.ietf.org/html/rfc7539#section-2.8.1
The check on aad_len allows us to stlightly optimize, but does not change the functionality.
In the low-level code this optimization further allows us to pass in null pointers.
So, this change is essentially about helping out low* code do something safe, it is not a functional change in the spec.
Am I right?

**Comment by beurdouche** [comment]
Correct, prevents the Low* code to do stack allocation and pointer arithmetic at execution for something that is gonna be discarded because of length zero. It doesn't change the functional behavior.

**Review by karthikbhargavan — APPROVED** [review]

**Pull request merged**
