### PR TITLE
remove cinline from some functions in ed25519

### PR DESCRIPTION
**Pull request by polubelova**
This PR is a follow-up to https://github.com/project-everest/hacl-star/pull/418

### CODE REVIEW

**Review by msprotz — APPROVED** [review]

**Comment by beurdouche** [comment]
I am curious about the performance regression for this, any idea ?

**Review by franziskuskiefer — APPROVED** [review]
I don't expect this to have a performance impact (smart compilers and all) but if we want to be 100% certain we'd of course have to test it.

**Comment by beurdouche** [comment]
That would be surprising, don’t we use load/store a lot?

**Comment by polubelova** [comment]
Most of these functions (except point_add and reduce_512) are used once. 
There is no perf diff if the code compiled with clang-9, just checked.

**Comment by franziskuskiefer** [comment]
> That would be surprising, don’t we use load/store a lot?

The compiler inlines if it thinks it makes sense. And probably does every time here, hence no performance difference because the actual result's probably the same.

**Pull request merged**
