### PR TITLE
Only register at-exit callback once

### PR DESCRIPTION
**Pull request by raphael-proust**
This aims to solve issue https://github.com/project-everest/hacl-star/issues/353

Note: this has not yet been tested.

### CODE REVIEW

**Comment by msprotz** [comment]
Thanks for the bugfix Raphaël! Would you or @victor-dumitrescu have any idea how to test this?

**Comment by victor-dumitrescu** [comment]
I've tested this using a simple loop that initialises an incremental hash and does a few updates. Indeed, the GC is invoked on exit the same number of times as the Hash was initialised, which I didn't expect when I first wrote this code. After applying this patch the GC is invoked only once. 

The difference in execution time is clearly noticeable. Initialising a SHA-256 hash 10.000 times, each time doing 10 updates, takes ~8s now and < 0.5s with this patch.

**Review by victor-dumitrescu — APPROVED** [review]

**Review by msprotz — APPROVED** [review]
Thanks. We still need CI to run and sadly it doesn't run for PRs from external forks. @victor-dumitrescu any chance you could push this to a private branch and just send a link here once you get a green, so that we can confirm this doesn't break anything? Thanks!

**Comment by victor-dumitrescu** [comment]
CI is passing on branch [vdum_354](https://github.com/project-everest/hacl-star/tree/vdum_354).

**Comment by msprotz** [comment]
Thanks!

For the record: I used my "administrator privileges" to merge this branch, because CI does not happen for PRs from external forks, and @victor-dumitrescu was able to confirm the change is green. This is to avoid having to open a separate PR and fragmenting the discussion.

**Pull request merged**
