### PR TITLE
fix build breakage in EverCrypt.Hash.Incremental

### PR DESCRIPTION
**Pull request by msprotz**
I suspect this will depend on other fixes... @mtzguido you may want to pull this into your branch first in order to get a green

### CODE REVIEW

**Comment by msprotz** [comment]
Note that the build failure is due to an OpenSSL cloning error and that the other CI job that was kicked as part of regular pushes came back green.

**Comment by prosecco** [comment]
Looks good.

**Comment by s-zanella** [comment]
Merging this to unblock CI. I'll add a comment in Makefile.common in a separate PR later.

**Comment by msprotz** [comment]
Sorry didn't intend to add the change to Makefile.common

**Pull request merged**
