### PR TITLE
Reduce ocaml dependencies

### PR DESCRIPTION
**Pull request by hhugo**

### CODE REVIEW

**Comment by hhugo** [comment]
@protz, this is a first step toward trying to use plain hacl-star with js_of_ocaml.

**Comment by msprotz** [comment]
Our CI system doesn't build external PRs so I've pushed your changes to origin/protz_remove_foreign just to see what the Hacl-Linux target (the important one) says. Thanks!

**Comment by msprotz** [comment]
Screen Shot 2021-11-13 at 10 18 03 AM

This is green -- thanks so much for the contribution!

**Review by msprotz — APPROVED** [review]

**Comment by msprotz** [comment]
@victor-dumitrescu you worked on this a lot, do you mind giving this a quick review? thanks!

**Comment by victor-dumitrescu** [comment]
Thanks for the PR and nice catch on spotting these unnecessary requirements. I think an early version did rely on ctypes.foreign but the current one indeed doesn't.

**Review by victor-dumitrescu — APPROVED** [review]

**Comment by hhugo** [comment]
When do you plan to make a new release ? I need this MR to compile hacl-star with jsoo

**Pull request merged**
