### PR TITLE
Aseem p256 memory

### PR DESCRIPTION
**Pull request by karthikbhargavan**
This PR fixes some proof failures after Aseem's memory consumption improvements.

### CODE REVIEW

**Comment by msprotz** [comment]
Thanks Aseem for the very much appreciated expert advice on how to lower the memory consumption. Nice proof fixes, Karthik -- thanks for improving P256. With that and my fixes in lib, I think we're a tiny bit better off now!

**Review by msprotz — APPROVED** [review]

**Comment by polubelova** [comment]
This looks good to me, thanks! Does this fix #539 and #541? If not completely, it would be nice to update the numbers.

The PR also touches @Frosne's proofs, so she might want to add something to the discussion.

**Review by polubelova — APPROVED** [review]

**Comment by msprotz** [comment]
I tried to reproduce the memory savings, but for some reason, I still saw 9GB on my Linux machine. I'll try to run the benchmark on my OSX machine once I'm back from Oakland to make sure I compare apples and apples.

**Comment by msprotz** [comment]
This is the measured peak memory usage with the current state of this PR:

```
2,171,124 Vale.AES.X64.AESGCM.fst
2,412,780 Vale.Poly1305.X64.fst
2,520,464 Hacl.Spec.K256.Field52.Lemmas3.fst
2,855,860 Spec.P256.MontgomeryMultiplication.PointAdd.fst
3,341,556 Vale.Wrapper.X64.GCMdecryptOpt256.fst
3,415,588 Vale.Wrapper.X64.GCMencryptOpt.fst
3,517,692 Vale.Wrapper.X64.GCMencryptOpt256.fst
3,535,744 Vale.Wrapper.X64.GCMdecryptOpt.fst
3,784,604 Vale.Curve25519.X64.FastUtil.fst
3,900,276 Vale.AES.X64.GCMdecryptOpt.fst
3,919,948 Vale.AES.X64.GCMencryptOpt.fst
3,945,136 Vale.Curve25519.X64.FastSqr.fst
4,090,340 Hacl.Test.ECDSA.fst
4,374,412 Vale.Curve25519.X64.FastHybrid.fst
5,575,540 Test.Vectors.fst
8,438,288 Hacl.Test.HMAC_DRBG.fst
9,493,064 Hacl.Impl.P256.LowLevel.fst
```

See https://github.com/project-everest/hacl-star/issues/541 for comparisons to:
- before this PR,
- after Aseem's memory fixes, but before Karthik's proof fixes

**Comment by karthikbhargavan** [comment]
@aseemr I need some help fixing the memory usage here.
Going back to your Ghost.hide style, the proof starts to fail, and apparently my current style the memory usage is high.
I don't fully understand the trade-off here, so some guidance and documentation on how to reduce memory use would be helpful. 
Or else we may need to rewrite the full proof.

**Comment by Frosne** [comment]
Hi!

I modified the P256 code that uses the calc expression you were talking about. I really hope that it will decreases the memory consumption!

**Comment by msprotz** [comment]
I would like to merge this. It contains numerous proof improvements beyond p256. We must resume work on p256 to diminish memory consumption again, but in the meanwhile, I want the good proof fixes to be on master. Any objection?

**Comment by Frosne** [comment]
@msprotz, I agree.

**Pull request merged**
