### PR TITLE
Remove miTLS support

### PR DESCRIPTION
**Pull request by msprotz**
Spurred by @polubelova's remark about EverCrypt.Specs, I decided to remove all of the stuff in the repo that was solely in support of legacy algorithms kept alive just for the sake of miTLS.

This is quite a bit.

Some of those wrappers would go back in a very limited form into the miTLS repository but I thought it'd be illuminating to see how much (unmaintained, unverified) code we could get rid of.

Things that are going:
- unverified aes-gcm code (circa 2016) written in a previous era, with prehistoric versions of HACL's "Lib" code, libraries, dependencies, etc.
- EverCrypt "stubs" around either OpenSSL or BCrypt, unverified and their corresponding unverified C wrappers
- old assemblies for AES-GCM + SHA256 written with old Vale/Dafny (circa 2016)
- ability to disable Vale, Hacl, OpenSSL or BCrypt at run-time: this was never used
- ability to choose between OpenSSL and BCrypt wrappers at compile-time: not actively used in ages
- build support and Makefile complexity for all of the above
- quic provider (written in C, needs a checkout of miTLS to verify, not actively maintained, superseded by everquic-crypto)

### CODE REVIEW

**Comment by msprotz** [comment]
45,000 lines of code removed -- that's a nice PR.

**Review by polubelova — APPROVED** [review]
This looks great, thanks Jonathan!

I think it's safe to remove `specs/old` as well.

**Comment by msprotz** [comment]
Everest Green: https://github.com/project-everest/everest/actions/runs/2778853872
Companion miTLS PR: https://github.com/project-everest/mitls-fstar/pull/254

The EverCrypt, EverCrypt.Specs, EverCrypt.OpenSSL and EverCrypt.Hacl placeholder modules are now in miTLS master, along with their respective C stubs.

**Review by karthikbhargavan — APPROVED** [review]
What's not to like. Great work, thanks!

**Pull request merged**
