### PR TITLE
Remove legacy AES which is no longer needed (as far as I know)

### PR DESCRIPTION
**Pull request by msprotz**

### CODE REVIEW

**Comment by msprotz** [comment]
Ok it's needed by the `master` branch of miTLS. Sigh. I can make sure it at least only exists in the dist/mitls folder

**Comment by beurdouche** [comment]
> Ok it's needed by the `master` branch of miTLS. Sigh. I can make sure it at least only exists in the dist/mitls folder

SGTM! Thanks Jonathan!

**Comment by msprotz** [comment]
Thanks. Do you and Tahina mind giving me a review of this?

**Review by beurdouche — APPROVED** [review]

**Review by tahina-pro — APPROVED** [review]

**Comment by msprotz** [comment]
Thanks Tahina! @beurdouche the next nightly build will take care of removing Hacl_AES everywhere except in dist/mitls

**Pull request merged**
